# Generated by Django 4.2 on 2023-06-11 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_inventoryproduct_quantity_and_more'),
        ('carts', '0005_remove_cart_product_alter_cart_user_delete_cartitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='city',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='products.city', verbose_name='شهر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('در حال ارسال', 'در حال ارسال'), ('در حال بررسی سفارش', 'درحال بررسی سفارش')], default='درحال بررسی سفارش', max_length=50, verbose_name='وضعیت سفارش'),
        ),
    ]
