# Generated by Django 4.2 on 2023-06-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_remove_cart_product_alter_cart_user_delete_cartitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('در حال بررسی سفارش', 'در حال بررسی سفارش'), ('در حال ارسال', 'در حال ارسال'), ('تحویل شده', 'تحویل شده')], default='در حال بررسی سفارش', max_length=50, verbose_name='وضعیت سفارش'),
        ),
    ]
