# Generated by Django 4.2 on 2023-06-11 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_inventoryproduct_inventoryid_and_more'),
        ('carts', '0006_orderitem_city_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.city', verbose_name='شهر'),
        ),
    ]
