# Generated by Django 4.2 on 2023-06-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_alter_orderitem_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('در حال ارسال', 'در حال ارسال'), ('در حال بررسی سفارش', 'درحال بررسی سفارش')], default='در حال ارسال', max_length=50, verbose_name='وضعیت سفارش'),
        ),
    ]
