# Generated by Django 4.2 on 2023-06-22 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_productvariation_text'),
        ('carts', '0008_orderitem_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خرید'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='انبار محصول'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariation', verbose_name='نام محصول'),
        ),
    ]
