# Generated by Django 4.2 on 2023-06-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_alter_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('در حال بررسی سفارش', 'در حال بررسی سفارش'), ('در حال ارسال', 'در حال ارسال')], default='در حال بررسی سفارش', max_length=50, verbose_name='وضعیت سفارش'),
        ),
    ]
