# Generated by Django 4.2 on 2023-06-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0011_remove_orderitem_cart_remove_orderitem_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='شهر'),
        ),
    ]
