# Generated by Django 4.2 on 2023-06-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0012_alter_order_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('در حال بررسی سفارش', 'در حال بررسی سفارش'), ('در حال ارسال', 'در حال ارسال'), ('تحویل شده', 'تحویل شده')], default='در حال بررسی سفارش', max_length=50, verbose_name='وضعیت سفارش'),
        ),
    ]
