# Generated by Django 4.2 on 2023-06-02 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cityId',
            new_name='city',
        ),
    ]
