# Generated by Django 4.2 on 2023-06-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(choices=[('تهران', 'تهران'), ('تبریز', 'تبریز')], max_length=50),
        ),
    ]
