# Generated by Django 4.2 on 2023-06-02 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_city_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
