# Generated by Django 4.2 on 2023-06-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(choices=[('تهران', 'تهران'), ('کرج', 'کرج'), ('تبریز', 'تبریز'), ('مشهد', 'مشهد'), ('اصفهان', 'اصفهان'), ('شیراز', 'شیراز'), ('قم', 'قم'), ('قشم', 'قشم'), ('کرمان', 'کرمان'), ('کردستان', 'کردستان')], max_length=50),
        ),
    ]
