# Generated by Django 4.2 on 2023-06-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('inventory', 'موجودی انبار'), ('ordered', 'سفارش')], default='inventory', max_length=10),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(choices=[('آبادان', 'آبادان'), ('بوشهر', 'بوشهر'), ('تهران', 'تهران'), ('کرج', 'کرج'), ('تبریز', 'تبریز'), ('مشهد', 'مشهد'), ('اصفهان', 'اصفهان'), ('شیراز', 'شیراز'), ('قم', 'قم'), ('قشم', 'قشم'), ('کرمان', 'کرمان'), ('کردستان', 'کردستان')], max_length=50),
        ),
    ]
