# Generated by Django 4.2 on 2023-06-16 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_status_alter_city_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='status',
            field=models.CharField(choices=[('موجود', 'موجودی انبار'), ('ناموجود', 'ناموجود')], default='موجود', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventoryproduct',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariation'),
        ),
    ]
