# Generated by Django 4.2 on 2023-06-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_status_inventoryproduct_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
