# Generated by Django 4.2 on 2023-06-28 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventoryproduct',
            name='status',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='Supplier',
            field=models.ManyToManyField(to='products.supplier'),
        ),
        migrations.AlterField(
            model_name='inventoryproduct',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='تعداد کالا'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='cityId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.city', verbose_name='انبار'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='name',
            field=models.CharField(max_length=30, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='price',
            field=models.IntegerField(help_text='یک بسته 500 گرمی', verbose_name='قیمت (تومان)'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='quantity',
            field=models.IntegerField(verbose_name='تعداد کالا'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='text',
            field=models.TextField(blank=True, help_text='اجبار پر کردن توضیحات نیست', max_length=1000, null=True, verbose_name='توضیح محصول'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contactInfo',
            field=models.IntegerField(verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(help_text='نام برند یا تامین کنندگان', max_length=50, verbose_name='نام تامین کنندگان'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory', verbose_name='دسته محصول'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
