# Generated by Django 4.2 on 2023-06-11 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productvariation_status_and_more'),
    ]

