# Generated by Django 4.2 on 2023-06-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productvariation_status'),
    ]

