# Generated by Django 4.2 on 2023-06-11 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_productvariation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='نام دسته بندی'),
        ),
    ]
