# Generated by Django 4.2 on 2023-06-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_status_remove_product_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryproduct',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cityId',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='cityId',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='توضیح کالا'),
        ),
    ]
