# Generated by Django 4.2 on 2023-06-11 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_inventoryproduct_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryproduct',
            name='inventoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.inventory', verbose_name='انبار'),
        ),
        migrations.AlterField(
            model_name='inventoryproduct',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariation', verbose_name='نام محصول'),
        ),
    ]
