# Generated by Django 4.2 on 2023-06-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_inventoryproduct_inventoryid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryproduct',
            name='status',
            field=models.CharField(choices=[('موجود', 'موجود'), ('ناموجود', 'ناموجود')], default='موجود', max_length=10),
        ),
    ]
